### ISSUE TITLE
suggestion: code example?

### ISSUE THREAD

**Issue by DeanKamali** [hcl1687/iframe-channel#2]
I'm a little overwhelmed with details, wondering if it's possible to provide demo example on codesandbox.io or codepen. 

Thanks

**Comment by hcl1687** [comment]
@DeanKamali 
Thank you for your attention
You can find all demos in the test/unit directory.
If you want to debug those demos, please follow the steps below:
1. Clone the project to your local computer.
2. Please type 'npm install' to install all package dependencies.
3. Please set singleRun to false, like this:
![image](https://user-images.githubusercontent.com/8159847/69408213-4fbc5780-0d41-11ea-834a-54deab596d85.png)
4. Please type 'npm run test'. Then Karma will lunch chrome browser. Like this:
![image](https://user-images.githubusercontent.com/8159847/69408395-bb062980-0d41-11ea-9697-b85e8664f968.png)
5. Press debug button, then you can debug all the demos. And I believe it will help you to understand it's details.
![image](https://user-images.githubusercontent.com/8159847/69408543-251ece80-0d42-11ea-9643-6c1737d0c4b7.png)


Currently,  I am a bit busy. I'll add demo example on codepen next Sunday.
Thank you.

**Comment by DeanKamali** [comment]
@hcl1687 Thanks for your help

**Comment by hcl1687** [comment]
@DeanKamali 
I have added demos. Please refer to the link in the readme file.
![image](https://user-images.githubusercontent.com/8159847/70147143-a67d4600-16de-11ea-8ce3-c8630d03ba40.png)

Initially, I considered writing the demo on codesandbox.io. But it's difficult to post message between two codesandbox page. So I just host the demo on my website. Please refer the online demo.

**Comment by DeanKamali** [comment]
@hcl1687 Thank you so much! your example has been very helpful.
